package com.example.android.todolist.database;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

import java.util.Date;

// TODO (2) Annotate the class with Entity. Use "task" for the table name
// Room will generate a table named "task"
// Our class is now entity that is associated with table named "task"
@Entity(tableName = "task")
public class TaskEntry {

    // TODO (3) Annotate the id of the task as PrimaryKey. Set autoGenerate to true.
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String description;
    private int priority;
    private Date updatedAt;

    // TODO (4) Use the Ignore annotation so Room knows that it has to use the other constructor instead
//    Ignores the marked element from Room's processing logic.
    // Room can use just 1 constructor, we let Room know using @Ignore
    // In order to add NEW task to DB, we need to create TaskEntry object, but ID will be autogenerated, that's why we have 2 constructors
    @Ignore
    public TaskEntry(String description, int priority, Date updatedAt) {
        this.description = description;
        this.priority = priority;
        this.updatedAt = updatedAt;
    }

    // For READING from the DB, Room will ask this! constructor to create TaskEntry object
    public TaskEntry(int id, String description, int priority, Date updatedAt) {
        this.id = id;
        this.description = description;
        this.priority = priority;
        this.updatedAt = updatedAt;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
